package starfederation.datastar;

import starfederation.datastar.enums.ElementPatchMode;

/**
 * This is auto-generated by Datastar. DO NOT EDIT.
 */
public final class Consts {
    public static final String DATASTAR_KEY = "datastar";
    public static final String VERSION = "1.0.0-RC.1";

    // The default duration for retrying SSE on connection reset. This is part of the underlying retry mechanism of SSE.
    public static final int DEFAULT_SSE_RETRY_DURATION = 1000;

    // Should elements be patched using the ViewTransition API?
    public static final boolean DEFAULT_ELEMENTS_USE_VIEW_TRANSITIONS = false;

    // Should a given set of signals patch if they are missing?
    public static final boolean DEFAULT_PATCH_SIGNALS_ONLY_IF_MISSING = false;

    // The mode in which an element is patched into the DOM.
    public static final ElementPatchMode DEFAULT_ELEMENT_PATCH_MODE = ElementPatchMode.Outer;

    // Dataline literals.
    public static final String SELECTOR_DATALINE_LITERAL = "selector ";
    public static final String MODE_DATALINE_LITERAL = "mode ";
    public static final String ELEMENTS_DATALINE_LITERAL = "elements ";
    public static final String USE_VIEW_TRANSITION_DATALINE_LITERAL = "useViewTransition ";
    public static final String SIGNALS_DATALINE_LITERAL = "signals ";
    public static final String ONLY_IF_MISSING_DATALINE_LITERAL = "onlyIfMissing ";
}