package starfederation.datastar.enums;

/**
 * This is auto-generated by Datastar. DO NOT EDIT.
 */
public enum ElementPatchMode {

    // Morphs the element into the existing element.
    Outer("outer"),

    // Replaces the inner HTML of the existing element.
    Inner("inner"),

    // Removes the existing element.
    Remove("remove"),

    // Replaces the existing element with the new element.
    Replace("replace"),

    // Prepends the element inside to the existing element.
    Prepend("prepend"),

    // Appends the element inside the existing element.
    Append("append"),

    // Inserts the element before the existing element.
    Before("before"),

    // Inserts the element after the existing element.
    After("after");

    private final String value;

    ElementPatchMode(String value) {
        this.value = value;
    }
    
    @Override
    public String toString() {
        return value;
    }
}