package starfederation.datastar.enums;

/**
 * This is auto-generated by Datastar. DO NOT EDIT.
 */
public enum EventType {

    // An event for patching HTML elements into the DOM.
    PatchElements("datastar-patch-elements"),

    // An event for patching signals.
    PatchSignals("datastar-patch-signals");

    private final String value;

    EventType(String value) {
        this.value = value;
    }
    
    @Override
    public String toString() {
        return value;
    }
}